# Rat data configuration file

# Raw data location
raw_data: ../data/raw/rat/14rat_data.xls

# Columns to keep from raw data
columns_to_keep:
  uniprot_id: Uniprot
  ensembl_id: ENSEMBL
  position: Position
  localization_prob: "Localization Prob"
  amino_acid: "Amino Acid"
  sequence_window: "Sequence Window"
  modified_sequence: "Modified Sequence"
  position_in_mod_seq: "Position in peptide"
  all_brain: "Total Brain #"
  cortex: "Cortex #"
  brainstem: "Brainstem #"
  cerebellum: "Cerebellum #"
  testicle: "Testicle #"
  pancreas: "Pancreas #"
  stomach: "Stomach #"
  liver: "Liver #"
  fat: "Fat #"
  intestine: "Intestine #"
  kidney: "Kidney #"
  spleen: "Spleen #"
  thymus: "Thymus #"
  lung: "Lung #"
  muscle: "Muscle #"
  heart: "Heart #"
  blood: "Blood #"
  total_ms_sum: "TOTAL MS SUM.1"

  
# Data cleaning filters:
filters:
  localization_min: 0.75

# Test Data settings:
sample_size: 20
random_state: 42