# Rat data configuration file

# Raw data location
raw_data: data/raw/rat/14rat_data.xls

# Columns to keep from raw data
columns_to_keep:
  uniprot_id: "Uniprot"
  ensembl_id: "ENSEMBL"
  protein_description: "Protein Descriptions"
  position: "Position"
  amino_acid: "Amino Acid"
  site_motif: "Sequence Window" # sequence windows of Â±6 residues adjacent to all serine and threonine phosphorylation sites
  modified_sequence: "Modified Sequence" # modifications of oxidation (M) (M(ox)), acetylation (protein N-term), Gln->pyro-Glu, and phosphorylation (STY).
  position_in_mod_seq: "Position in peptide"
  total_tissue_num: "TOTAL MS SUM.1" 
  all_brain: "Total Brain #"
  cortex: "Cortex #"
  brainstem: "Brainstem #"
  cerebellum: "Cerebellum #"
  testicle: "Testicle #"
  pancreas: "Pancreas #"
  stomach: "Stomach #"
  liver: "Liver #"
  fat: "Fat #"
  intestine: "Intestine #"
  kidney: "Kidney #"
  spleen: "Spleen #"
  thymus: "Thymus #"
  lung: "Lung #"
  muscle: "Muscle #"
  heart: "Heart #"
  blood: "Blood #"
  localization: "Localization Prob" # a probability from 0-1, filter out all less than 0.75
  
# Data cleaning filters:
filters:
  localization:
    type: numerical
    column: "localization"
    threshold: 0.75
  required_ids: ["uniprot_id", "ensembl_id"] 